export default [
  { src: "avatar1.png", label: "Avatar 1", id: 1 },
  { src: "avatar2.png", label: "Avatar 2", id: 2 },
  { src: "avatar3.png", label: "Avatar 3", id: 3 },
  { src: "avatar4.png", label: "Avatar 4", id: 4 },
  { src: "avatar5.png", label: "Avatar 5", id: 5 },
  { src: "avatar6.png", label: "Avatar 6", id: 6 },
  { src: "avatar7.png", label: "Avatar 7", id: 7 },
  { src: "avatar8.png", label: "Avatar 8", id: 8 },
  { src: "avatar9.png", label: "Avatar 9", id: 9 },
  { src: "avatar10.png", label: "Avatar 10", id: 10 },
  { src: "avatar11.png", label: "Avatar 11", id: 11 },
  { src: "avatar12.png", label: "Avatar 12", id: 12 },
  { src: "avatar13.png", label: "Avatar 13", id: 13 },
  { src: "avatar14.png", label: "Avatar 14", id: 14 },
  { src: "avatar15.png", label: "Avatar 15", id: 15 },
  { src: "avatar16.png", label: "Avatar 16", id: 16 },
  { src: "avatar17.png", label: "Avatar 17", id: 17 },
  { src: "avatar18.png", label: "Avatar 18", id: 18 },
  { src: "avatar19.png", label: "Avatar 19", id: 19 },
  { src: "avatar20.png", label: "Avatar 20", id: 20 },
];
